---
- name: Install SQL Server Driver for Wildfly on Windows
  hosts: '{{ target_hosts }}'

  tasks:
    - name: set JAVA_HOME as facts
      set_fact:
        java_home: '{{ ansible_env.ProgramFiles }}\Java\jdk1.{{ java_major_version }}_{{ java_minor_version }}'

    - name: set JBOSS_HOME as facts
      set_fact:
        jboss_home: '{{ ansible_env.SystemDrive }}\WildFly\wildfly-{{ wildfly_version }}'

    - name: create mssql module directory
      win_file:
        path: '{{ jboss_home }}\modules\system\layers\base\com\microsoft\sqlserver\main'
        state: directory

    - name: copy mssql jdbc jar module
      win_copy:
        src: '{{ mssql_jdbc_jar }}.jar'
        dest: '{{ jboss_home }}\modules\system\layers\base\com\microsoft\sqlserver\main\{{ mssql_jdbc_jar }}.jar'

    - name: copy mssql jdbc jar module.xml
      win_copy:
        src: '{{ mssql_jdbc_jar }}.module.xml'
        dest: '{{ jboss_home }}\modules\system\layers\base\com\microsoft\sqlserver\main\module.xml'

    - name: check installed mssql jdbc driver
      win_shell: |
        {{ jboss_home }}\bin\jboss-cli.bat --connect --controller={{ ansible_host }}:9990 --commands="ls subsystem=datasources/jdbc-driver=mssql"
      environment:
        JAVA_HOME: '{{ java_home }}'
        JBOSS_HOME: '{{ jboss_home }}'
        NOPAUSE: 'true'
      ignore_errors: true
      register: mssql_rc

    - name: install mssql jdbc driver
      win_shell: |
        {{ jboss_home }}\bin\jboss-cli.bat --connect --controller={{ ansible_host }}:9990 --commands="/subsystem=datasources/jdbc-driver=mssql:add(driver-name=mssql,driver-module-name=com.microsoft.sqlserver,driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver,driver-xa-datasource-class-name=com.microsoft.sqlserver.jdbc.SQLServerXADataSource)"
      environment:
        JAVA_HOME: '{{ java_home }}'
        JBOSS_HOME: '{{ jboss_home }}'
        NOPAUSE: 'true'
      when: mssql_rc.rc != 0

    - name: stop wildfly service
      win_shell: |
        {{ jboss_home }}\bin\jboss-cli.bat --connect --controller={{ ansible_host }}:9990 --commands=shutdown
      environment:
        JAVA_HOME: '{{ java_home }}'
        JBOSS_HOME: '{{ jboss_home }}'
        NOPAUSE: 'true'

    - name: set wildfly service startup mode to auto and ensure it is started
      win_service:
        name: '{{ wildfly_service_name }}'
        start_mode: auto
        state: started
