---
- name: WildFly Management Check
  hosts: '{{ target_hosts }}'

  tasks:
    - name: check if wildfly deployed well
      local_action:
        module: uri
        url: http://{{ ansible_host }}:8080/
        method: GET
        status_code: 200
